Task1 in lab2
osenkoff/OOP pull request #4
Opened 2024-10-30 11:39 UTC by osenkoff

2024-11-01 07:24 UTC, pechischev requested changes
в целом уже не плохо, значительный прогресс есть по сравнению с первой лабой 👍

2024-11-01 07:24 UTC, pechischev commented on lab2/pubspec.yaml
> +  test: ^1.24.0
совет на будущее - лучше фиксировать версии пакетов (не указывать ^), потому что есть тенденция обновления пакетов, и иногда у этих пакетов есть ломающие изменения. И вместо спокойного запуска придется чинить проект

2024-11-01 07:24 UTC, pechischev commented on lab2/CHANGELOG.md
> +- Initial version.
это кстати полезная штука для будущих проектов

2024-11-01 07:24 UTC, pechischev commented on lab2/lib/task1/main.dart
> +  var parser = ArgParser()
можно сделать намного лучше и гибче, попробуй реализовать обработку команды с помощью [команд](https://pub.dev/packages/args#dispatching-commands). Такой подход позволит создать независимые куски функционала и сделать код намного расширяемым

ну и негласное правило для main - нужно стараться держать в main минимальное кол-во кода и только связанным с инициализацией команд и выводом результатов, все остальное можно выносить в другие файлы

2024-11-01 07:24 UTC, pechischev commented on lab2/lib/task1/main.dart
> +List<double> _fillArray() {
название fill путает, будто заполняется массив, но не слова про инициализацию массива через консоль (я не сразу догадался, пока реализацию не посмотрел)

лучше будет к примеру такое название `getDigitsFromConsole`

по хорошему, названия нужно давать такие, чтобы по месту использования было понятно, что делает функция, и не нужно было заходить внутрь реализации этой функции

2024-11-01 07:24 UTC, pechischev commented on lab2/lib/task1/actions.dart
> +  List<double> selectAction({
а вот теперь самое интересное будет: первое использование паттерна)

с помощью паттерна [Стратегия](https://refactoring.guru/ru/design-patterns/strategy) нужно переделать этот код (открывай под ВПН)

2024-11-01 07:24 UTC, pechischev commented on lab2/lib/task1/actions.dart
> +    updatedArray = updatedArray.sorted((a, b) => a.compareTo(b));
а сортировка на каждое действие нужна?

2024-11-01 07:24 UTC, pechischev commented on lab2/lib/task1/actions.dart
> +      );
а вот такое сообщение лучше делать там, где располагается работа с консолью. Потому что в сообщении есть инфа о командах для консоли. Если вдруг поменяется команда на получение помощи, то придется вместо одного файла менять и тут (если вообще не забудется про это). Лучше держать связанные вещи рядом, а не раскидывать по всему проекту

2024-11-01 07:24 UTC, pechischev commented on lab2/lib/task1/actions.dart
> +                : updatedArray.add(receivedArray[i] * 2);
так лучше не делай: унарный оператор + операция - сейчас это только усложняет код

унарный оператор обычно применяют для **_получения_** какого-то значения для переменной
лучше сделай так (будет более читабельно и уберется дублирование с updatedArray.add)
```dart
// пример
final someVar = (condition) ? digit - sum : digit *2;
array.add(someVar);
```

2024-11-01 07:24 UTC, pechischev commented on lab2/lib/task1/actions.dart
> +            (i % 2 == 0 || i == 0)
если что 0 тоже типа четное число: 0 % 2 даст 0
так что отдельная проверка i == 0 не даст ничего

2024-11-01 07:24 UTC, pechischev commented on lab2/lib/task1/actions.dart
> +        case '1':
для каждого кейса напиши пожалуйста в комментах, что должно делаться
чтобы в задания не лазить каждый раз

2024-11-01 07:24 UTC, pechischev commented on lab2/lib/task1/actions.dart
> +        case '1':
ну и все методы average, min, max, которые есть в List, реализуй плиз самостоятельно (это только для этого задания)

2024-11-01 12:34 UTC, osenkoff commented on lab2/CHANGELOG.md
> +- Initial version.
Для чего вообще этот файлик нужен? Помимо контроля версии? И как его правильно заполнять?

2024-11-01 14:08 UTC, pechischev commented on lab2/CHANGELOG.md
> +- Initial version.
Он нужен, чтобы отписывать историю изменений, типа указывается версия и список того, что изменилось. Он в приложениях или пакетах используется, тебе по сути он щас вообще не нужен

2024-11-01 14:09 UTC, pechischev commented on lab2/CHANGELOG.md
> +- Initial version.
Но если интересно , то посмотри  в инете как он заполняется

2024-11-12 10:26 UTC, osenkoff commented on lab2/lib/task1/actions.dart
> +    updatedArray = updatedArray.sorted((a, b) => a.compareTo(b));
![Screenshot 2024-11-12 132547](https://github.com/user-attachments/assets/aa17bc41-d957-429f-8cb7-c958218cfdcd)


Я сделал вроде как, по заданию, но была идея сделать запрос с консоли на то, сортировать или нет

2024-11-12 10:27 UTC, osenkoff commented
![image](https://github.com/user-attachments/assets/adb3a403-2780-4078-afd3-115dc2335a2a)

Task

2024-11-13 19:37 UTC, osenkoff commented on lab2/lib/task1/actions.dart
> +  List<double> selectAction({
Сделал страту только для функций листа, если норм будет, переделаю уже Actions

2024-11-13 19:47 UTC, osenkoff commented on lab2/lib/task1/actions.dart
> +    updatedArray = updatedArray.sorted((a, b) => a.compareTo(b));
Пока что сортировку убрал, потом скажи, как лучше сделать её

2024-11-14 07:46 UTC, osenkoff commented on lab2/lib/task1/actions.dart
> +  List<double> selectAction({
Нашёл ещё несколько вариантов, помимо твоего, что про них скажешь? Насколько они качественные?
https://medium.com/flutter-community/design-patterns-strategy-pattern-in-dart-7c833812d58d
https://scottt2.github.io/design-patterns-in-dart/strategy/

2024-11-14 12:32 UTC, pechischev commented on lab2/lib/task1/actions.dart
> +  List<double> selectAction({
в целом они нормальные как пример паттерна, так что можешь брать на заметку. Главное в паттерне понять принцип реализации и для решения какой проблемы его придумали

2024-11-14 14:09 UTC, osenkoff commented on lab2/lib/task1/actions.dart
> +  List<double> selectAction({
Насколько, кстати, будет кончено делать стратегию в стратегии? Если я сейчас сделал страту для функций листа, а потом страту для экшенов юзану?

2024-11-14 17:14 UTC, pechischev commented on lab2/lib/task1/actions.dart
> +import './strategy/mathematical_strategy/select_operation.dart';
можно не делать слишком большую вложенность, можно просто сделать

- operations
-- <operation-name>_strategy.dart

2024-11-14 17:14 UTC, pechischev commented on lab2/lib/task1/main.dart
> +import 'package:lab2/task1/commands/choose_command.dart';
сокращая импорты, особенно если файл рядом лежит

2024-11-14 17:14 UTC, pechischev commented on lab2/lib/task1/actions.dart
> +  List<double> selectAction({
стратегия в стратегии - это уже другой паттерн - Декоратор

лучше сделать так, чтобы каждая стратегия отвечала за вариант программы (8 вариантов = 8 стратегии)
т.е. получится, что у тебя 8 поведений программы. Слишком делить не надо, возрастет сложность программы

2024-11-14 17:14 UTC, pechischev commented on lab2/lib/task1/actions.dart
> +    updatedArray = updatedArray.sorted((a, b) => a.compareTo(b));
лучше ее сделать перед выводом в консольку

2024-11-14 17:14 UTC, pechischev commented on lab2/lib/task1/strategy/mathematical_strategy/mathematical_strategy.dart
> +class GetMinimalValueStrategy implements MathematicalStrategy {
чутка неверно сделано - эти стратегии лучше просто сделать функциями
вроде
```
double min(array) { ... }

double max(array) { ... }

...
```

2024-11-14 17:14 UTC, pechischev commented on lab2/lib/task1/actions.dart
> +          operation.setOperation(GetMinimalValueStrategy());
весь код, расположенный в case, нужно вынести в стратегии

по факту у тебя должно получиться вроде такого кода
```dart
final variantType = getVariantFromConsole();
final variant = getVariant(variantType); // внутри будет присваиваться нужная стратегия и выдаваться сюда

final result = variant.execute(arrayFromConsole);
// ...
```

2024-11-24 20:00 UTC, pechischev commented on lab2/lib/task1/strategy/action_strategy.dart
> +        : averageNumber = 0;
уже писал про использование тенарного условия, стоит использовать либо 
`final averageNumber = evenNumbers.isNotEmpty ?`operation.average(evenNumbers) : 0;
либо через if-else
```
final averageNumber = 0;
if (evenNumbers.isNotEmpty) {
   averageNumber = operation.average(evenNumbers);
}
```

2024-11-24 20:00 UTC, pechischev commented on lab2/lib/task1/strategy/mathematical_strategy.dart
> +class ExecuteOperationStrategy implements MathematicalStrategy {
да блин, это не стратегия, а утилиты, типа такого - https://pub.dev/packages/basic_utils

интерфейс тут не нужен, класс обзови как MathUtils и все функции сделай static, чтобы вызывать функцию без необходимости создавать класс

2024-11-24 20:00 UTC, pechischev commented on lab2/lib/task1/strategy/mathematical_strategy.dart
> +  double length(List<double> array) => array.fold(0, (total, _) => total + 1);
length можно не реализовывать, собственная реализация будет намного хуже по скорости той, которая предоставляется стандартно

2024-11-26 18:15 UTC, osenkoff commented on lab2/lib/task1/strategy/mathematical_strategy.dart
> +class ExecuteOperationStrategy implements MathematicalStrategy {
В каком случае выгодно для класса делать статик функции?

2024-11-26 20:07 UTC, pechischev commented on lab2/lib/task1/strategy/mathematical_strategy.dart
> +class ExecuteOperationStrategy implements MathematicalStrategy {
несколько причин:
- когда требуется вызвать функцию без инициализации класса
- когда спокойно можно вынести функцию за пределы класса, но по смыслу она должна быть частью класса 

про особенности статик функций можешь тут почитать: https://www.educative.io/answers/what-are-static-methods-in-dart

2024-11-26 20:12 UTC, pechischev approved these changes
можешь сливать

в отдельной ветке сделаешь тесты для этого задания:
- каждая стратегия  в отдельном файле (позитивные и негативные кейсы под каждый вариант свои будут)
- тесты для математических функций, чтобы быть уверенным, что они работают нормально

итогом должно быть:
- файлы с тестами по стратегиям
- файл с тестами по мат операциям
- скриншот пройденных тестов

2024-11-26 20:15 UTC, pechischev commented
можешь кстати дать осмысленные названия вариантам стратегиям по тому, что они делают

2024-12-12 18:40 UTC, merged