Added tests to the lab2_task1
osenkoff/OOP pull request #5
Opened 2024-12-12 18:41 UTC by osenkoff

2024-12-13 13:04 UTC, osenkoff commented
**1) Maths_Utils**
![image](https://github.com/user-attachments/assets/aee0ab97-bda8-41bf-8cf8-92cbc59a67d5)

2) **First Strategy**
![image](https://github.com/user-attachments/assets/e38773b2-322c-4f0f-8c36-25f0f26761a3)

3) **Second Strategy**
![image](https://github.com/user-attachments/assets/e47161b0-d661-4e82-b854-aa4cb7257f0b)

4) **Third Strategy**
![image](https://github.com/user-attachments/assets/f6cc5891-b67f-4014-a8ea-afaf260d8f2a)

5) **Fourth Strategy**
![image](https://github.com/user-attachments/assets/1dca3893-970a-460e-b8ed-9b9869286f4b)

6) **Fifth Strategy**
![image](https://github.com/user-attachments/assets/87e91a28-13ed-4b9a-83d8-17fe9d22499c)

7) **Sixth Strategy**
![image](https://github.com/user-attachments/assets/8980a168-20c1-455e-a69e-a1ac371e1d54)

8) **Seventh Strategy**
![image](https://github.com/user-attachments/assets/3bc9cf72-fab5-4402-bcd6-8078cba97431)

9) **Eighth Strategy**
![image](https://github.com/user-attachments/assets/0d77e58e-4df6-41cc-a06e-ea21641c2936)

2025-01-09 15:58 UTC, pechischev requested changes
исправь ошибки

2025-01-13 18:04 UTC, pechischev commented on lab2/lib/task1/strategy/action_strategy.dart
> +  List<double> performAction(List<double> array);
сделай @protected функцией - https://medium.com/@nijatnamazzade/protected-keyword-in-dart-b8b8ef024c89

2025-01-13 18:04 UTC, pechischev commented on lab2/test/action_strategy_test/multiply_max_div_min_strategy_test.dart
> +    var multiplyMaxDivMinStrategy = MultiplyMaxDivMinStrategy();
сразу в main можешь объявить стратегию, чтобы не делать для каждой группы, ибо бессмысленно

2025-01-16 21:19 UTC, osenkoff commented on lab2/test/action_strategy_test/multiply_max_div_min_strategy_test.dart
> +    var multiplyMaxDivMinStrategy = MultiplyMaxDivMinStrategy();
![image](https://github.com/user-attachments/assets/aff64037-ecfb-47ab-a5f8-00a9dcc9432d)
![image](https://github.com/user-attachments/assets/842cc08d-f96f-4713-97d7-8a7d62bf4028)

Для негативных тестов он требует личное объявление

2025-01-17 06:36 UTC, pechischev approved these changes

2025-01-17 06:36 UTC, pechischev commented on lab2/test/action_strategy_test/multiply_max_div_min_strategy_test.dart
> +    // var multiplyMaxDivMinStrategy = MultiplyMaxDivMinStrategy();
походу забыл удалить

2025-01-17 09:13 UTC, merged